DROP TABLE IF EXISTS TB_MOVIE;
CREATE TABLE TB_MOVIE (  
ID_MOVIE INT AUTO_INCREMENT  PRIMARY KEY,
MOVIE_YEAR INT NOT NULL,  
TITLE VARCHAR(255) NOT NULL,
STUDIO VARCHAR(255) NOT NULL,
PRODUCERS VARCHAR(255) NOT NULL,
WINNER INT NOT NULL  
);  